apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
      - name: swiggy-app
        image: 654654349563.dkr.ecr.us-east-2.amazonaws.com/sush:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
